[project]
name = "ascii-art-generator"
version = "0.1.0"
dependencies = [
    "Pillow",
    "numpy",
    "opencv-python-headless",
    "rembg>=2.0.50",
    "onnxruntime",
    "tqdm",
    "numba>=0.59.0",
]

[project.scripts]
pyscii = "ascii_art_generator.main:main"
